Dockerfile, README.md
ISSUE-4
Forgot to remove `mkdir` and COPY commands
=> issue-4 Remove mkdir and COPY commands

README.md
=> issue-4 Improve documentation

Dockerfile, senzing-example-notebooks/python/README.md
ISSUE-10
Competing pip and anaconda installations.
Settle on anaconda installation.
Change suggested by "GKA"
=> Initial changes

Dockerfile
=> issue-13 Added code to get signing key for mySQL

.pydevproject, Dockerfile
ISSUE-15
Standardize on BASE_IMAGE
=> issue-15 Changed BASE_CONTAINER to BASE_IMAGE

Dockerfile, README.md, rootfs/app/docker-entrypoint.sh, rootfs/etc/odbc.ini.db2-template, rootfs/etc/odbc.ini.mysql-template, rootfs/etc/odbc.ini.postgresql-template, rootfs/etc/odbcinst.ini.template, rootfs/opt/IBM/db2/clidriver/cfg/db2dsdriver.cfg.db2-template
ISSUE-15
Refactored to remove components needing EULA.
=> issue-15 Working docker image with database

README.md
=> issue-15 long-form cli options

README.md
=> issue-15 Links to notebooks

README.md, googleba82b8a72a6018e9.html, notebooks/senzing-examples/python/senzing-addDataSource.html
=> issue-23 HTML version of Jupyter notebook

README.md
=> issue-23  Document improvement

.gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, Dockerfile, docker-compose.test.yml, docs/simplified-instructions-for-windows.md, robots.txt, rootfs/app/container-test.sh, rootfs/app/healthcheck.sh
=> issue-23 Passed inspectDockerImage

README.md
=> sudo docker

README.md
=> Issue 37.dockter.2

notebooks/senzing-examples/java/Senzing-G2Engine(Java).ipynb
=> Add G2Engine for java

CHANGELOG.md, Dockerfile
=> issue-43 Prepare for 1.1.0

CHANGELOG.md
=> issue-43 Fixed initV2() comments

README.md
=> issue-43 Update to template

.dockerignore, CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, README.md
=> issue-49 Add MSSQL support. Refactor to template

README.md
=> issue-49 Refactor to template 

README.md
=> issue-49 Fix typo

Makefile, README.md
=> issue-53 Refactor to template

notebooks/senzing-examples/python/senzing-G2Engine-whyEntity.ipynb
=> #57 Initial draft

notebooks/senzing-examples/python/senzing-G2Audit-getSummaryData.ipynb, notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/python/senzing-G2Config.ipynb, notebooks/senzing-examples/python/senzing-G2ConfigMgr.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/python/senzing-G2Engine.ipynb, notebooks/senzing-examples/python/senzing-G2Product-license.ipynb, notebooks/senzing-examples/python/senzing-G2Product-version.ipynb
=> #61 Modified H1 titles to avoid collision with HTML anchors

README.md, notebooks/senzing-examples/python/senzing-G2Audit-getSummaryData.ipynb, notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/python/senzing-G2Config.ipynb, notebooks/senzing-examples/python/senzing-G2ConfigMgr.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/python/senzing-G2Engine.ipynb, notebooks/senzing-examples/python/senzing-G2Product-license.ipynb, notebooks/senzing-examples/python/senzing-G2Product-version.ipynb
=> issue-61 Improve hyperlinks

README.md
=> issue-61 Add reference to nbviewer.jupyter.org

notebooks/senzing-examples/python/senzing-G2Audit-getSummaryData.ipynb, notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/python/senzing-G2Product-license.ipynb, notebooks/senzing-examples/python/senzing-G2Product-version.ipynb
Issue number: #61 
???
Add a table of contents to python notebooks
=> Issue 61.macy.1

.gitignore, notebooks/senzing-examples/python/senzing-create-redo-records.ipynb
=> issue-77 Notebook showing how to create redo record

CHANGELOG.md
=> #81 Added 1.1.15

Dockerfile
=> Install nbextensions

docs/senzing-G2Engine-reference.html
=> #90 Add HTML version of G2Engine reference

docs/index.html
=> #90 Add index.html

docs/index.html, docs/java-executed/index.html, docs/java/index.html, docs/python-executed/index.html, docs/python-executed/senzing-G2Audit-getSummaryData.html, docs/python-executed/senzing-G2Config-addDataSource.html, docs/python-executed/senzing-G2Config-reference.html, docs/python-executed/senzing-G2ConfigMgr-reference.html, docs/python-executed/senzing-G2Engine-addRecord.html, docs/python-executed/senzing-G2Engine-exportConfig.html, docs/python-executed/senzing-G2Engine-reference.html, docs/python-executed/senzing-G2Engine-stats.html, docs/python-executed/senzing-G2Engine-whyEntity.html, docs/python-executed/senzing-G2Product-license.html, docs/python-executed/senzing-G2Product-version.html, docs/python-executed/senzing-create-redo-records.html, docs/python/index.html, notebooks/senzing-examples/python/senzing-G2Config-reference.ipynb, notebooks/senzing-examples/python/senzing-G2ConfigMgr-reference.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-reference.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/python/senzing-G2Product-license.ipynb, notebooks/senzing-examples/python/senzing-create-redo-records.ipynb
=> Issue 90.macy.5

notebooks/senzing-examples/java/senzing-G2Config-reference.ipynb, notebooks/senzing-examples/python/senzing-G2Config-reference.ipynb
Issue number: #98
Update the titles of v2 functions
=> Issue 98.macy.1

notebooks/senzing-examples/python/senzing-G2Config-reference.ipynb
Issue number: #99
Methods were missing
=> #99 add missing methods

.gitmodules
=> Issue 115.macy.1

Dockerfile
=> #123 BASE_IMAGE=jupyter/minimal-notebook:ubuntu-18.04 work-around

CHANGELOG.md
=> #123 Prepare for version

notebooks/senzing-examples/python/senzing-init-config.ipynb
=> #127 add suport for cluster databases

notebooks/senzing-examples/java/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/java/senzing-G2Product-license.ipynb, notebooks/senzing-examples/java/senzing-G2Product-version.ipynb, notebooks/senzing-examples/java/senzing-create-redo-records.ipynb
=> #128 add support for cluster databases

CHANGELOG.md, README.md
=> Update to senzingdata 2.0.0

CHANGELOG.md, Dockerfile, notebooks/senzing-examples/java/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/java/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/java/senzing-G2Product-license.ipynb, notebooks/senzing-examples/java/senzing-G2Product-version.ipynb, notebooks/senzing-examples/java/senzing-create-redo-records.ipynb, notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/python/senzing-G2Product-license.ipynb, notebooks/senzing-examples/python/senzing-G2Product-version.ipynb, notebooks/senzing-examples/python/senzing-create-redo-records.ipynb, notebooks/senzing-examples/python/senzing-init-config.ipynb
=> Update for V3

CONTRIBUTING.md, README.md, docs/simplified-instructions-for-macos.md, docs/simplified-instructions-for-windows.md, notebooks/senzing-examples/Windows/README.md
=> #142 Migrate from master to main

.gitmodules, CHANGELOG.md, Dockerfile, Makefile
=> Issue 147.dockter.1

CHANGELOG.md, Dockerfile, notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-addRecord.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-exportConfig.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-stats.ipynb, notebooks/senzing-examples/python/senzing-G2Engine-whyEntity.ipynb, notebooks/senzing-examples/python/senzing-G2Product-license.ipynb, notebooks/senzing-examples/python/senzing-G2Product-version.ipynb, notebooks/senzing-examples/python/senzing-create-redo-records.ipynb, notebooks/senzing-examples/python/senzing-init-config.ipynb, notebooks/senzing-examples/python/senzing-init-files.ipynb
=> Issue 157.dockter.1

CHANGELOG.md, Dockerfile
=> #157 Update dates

Dockerfile
=> Remove psutil
